name: smart_traffic_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.12.0
  english_words: ^4.0.0
  provider: ^6.1.5
  syncfusion_flutter_gauges: ^25.1.38
  vibration: ^2.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flying_car.riv


