name: smart_traffic_app
description: "A Flutter application for smart traffic management"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.4
  firebase_auth_web: ^5.4.2
  cloud_firestore: ^4.8.5
  google_sign_in: ^6.1.7
  google_sign_in_web: ^0.12.2
  # UI & State Management
  provider: ^6.1.5
  # Maps & Location
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.5.3
  geolocator: ^10.1.0
  # Local Storage
  shared_preferences: ^2.5.4
  # Media
  image_picker: ^1.0.7
  # File & Path
  path_provider: ^2.1.2
  path: ^1.8.3
  # Animation
  rive: ^0.12.0
  # Utils
  vibration: ^2.0.0
  english_words: ^4.0.0
  http: ^0.13.5
  intl: ^0.19.0
  # Google Maps & Places
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places: 0.3.0
  google_api_headers: ^5.3.2
  # Gauges
  syncfusion_flutter_gauges: ^20.4.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flying_car.riv